// File generated by FlutterFire CLI & configured for Patient Portal.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs75asELVGpCS5OdVdtWEXMHkXAV1X7IE',
    appId: '1:847039075939:web:79c1f4155251c2e4d3ca56',
    messagingSenderId: '847039075939',
    projectId: 'patient-portal-innsof',
    authDomain: 'patient-portal-innsof.firebaseapp.com',
    storageBucket: 'patient-portal-innsof.firebasestorage.app',
    measurementId: 'G-WHP89T17V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjjfFXXL1o6pkOODhCJV9ZFYkPWO3RAs4',
    appId: '1:405705533040:android:ce7cea6ca86585adaf76b5',
    messagingSenderId: '405705533040',
    projectId: 'patient-portal-innsof-ad10d',
    storageBucket: 'patient-portal-innsof-ad10d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKPV4LzP8hJH95hYT5_wkOvNupGWMlCQ',
    appId: '1:405705533040:ios:b3ea3e6fa0f036f2af76b5',
    messagingSenderId: '405705533040',
    projectId: 'patient-portal-innsof-ad10d',
    storageBucket: 'patient-portal-innsof-ad10d.firebasestorage.app',
    iosBundleId: 'com.example.patientPortal',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXPN1QfQG4epzAgHugrNw_RpwgNuS7K6w',
    appId: '1:847039075939:ios:4eab6ffec6f98acdd3ca56',
    messagingSenderId: '847039075939',
    projectId: 'patient-portal-innsof',
    storageBucket: 'patient-portal-innsof.firebasestorage.app',
    iosBundleId: 'com.example.patientPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs75asELVGpCS5OdVdtWEXMHkXAV1X7IE',
    appId: '1:847039075939:web:0bf2df3a94d63ae4d3ca56',
    messagingSenderId: '847039075939',
    projectId: 'patient-portal-innsof',
    authDomain: 'patient-portal-innsof.firebaseapp.com',
    storageBucket: 'patient-portal-innsof.firebasestorage.app',
    measurementId: 'G-CH4647EGBD',
  );
}
